# Generated by Django 4.1.3 on 2022-11-17 07:58

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Newsletter',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, unique=True)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Draft', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('email', models.ManyToManyField(blank=True, to='newsletter.newsletter')),
            ],
            options={
                'verbose_name_plural': 'Newsletters',
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='newsletter',
            index=models.Index(fields=['email'], name='newsletter__email_350e42_idx'),
        ),
        migrations.AddIndex(
            model_name='newslettertext',
            index=models.Index(fields=['subject'], name='newsletter__subject_2dafa3_idx'),
        ),
    ]
